// AUTO-GENERATED by Phase 179 worker — see .beastmode/worker-runs/<ts>/prompt.md
import type { LucideIcon } from "lucide-react";
import {
  // Brand icons (Slack, Notion, Github) are not in lucide-react@1.7.0;
  // we use semantic equivalents until a brand-pack is added.
  MessageCircle, // Slack stand-in (chat)
  FileText, // Notion stand-in (docs)
  GitBranch, // GitHub stand-in (source control)
  Cloud,
  MessageSquare,
  Users,
  Banknote,
  Receipt,
  Calendar,
  Database,
  Box,
  Video,
  LayoutGrid,
  Layers,
  Code2,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ProviderCategoryId =
  | "productivity"
  | "developer"
  | "crm"
  | "finance"
  | "other";

export type AuthMode = "oauth" | "api-key";

interface ProviderBase {
  /** Unique id; used as the Nango integration id. Lowercase, hyphen-safe. */
  key: string;
  /** Human-readable label shown in the connect CTA. */
  label: string;
  /** Lucide icon component. */
  icon: LucideIcon;
  /** Short one-line description for the directory card. */
  description: string;
  /** Category bucket. */
  category: ProviderCategoryId;
  /** Auth mode (this slice is single-mode only). */
  authMode: AuthMode;
}

export interface OAuthProvider extends ProviderBase {
  authMode: "oauth";
  /** Nango provider-config key (the slug registered in Nango). */
  providerConfigKey: string;
  /** OAuth scopes to request when initiating the connect flow. */
  scopes: string[];
}

export interface ApiKeyProvider extends ProviderBase {
  authMode: "api-key";
  /** Label/placeholder for the API key input field. */
  apiKeyField: string;
  /** Link to the docs page where the user obtains the key. */
  docsUrl: string;
}

export type Provider = OAuthProvider | ApiKeyProvider;

export interface ProviderCategory {
  id: ProviderCategoryId;
  label: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Categories (ordered — the order here is the directory order)
// ---------------------------------------------------------------------------

export const PROVIDER_CATEGORIES: readonly ProviderCategoryId[] = [
  "productivity",
  "developer",
  "crm",
  "finance",
  "other",
] as const;

const CATEGORY_META: Record<ProviderCategoryId, ProviderCategory> = {
  productivity: {
    id: "productivity",
    label: "Productivity",
    description: "Docs, chat, calendars, and team workspaces.",
  },
  developer: {
    id: "developer",
    label: "Developer",
    description: "Source control, infra, and engineering tools.",
  },
  crm: {
    id: "crm",
    label: "CRM & Sales",
    description: "Contacts, pipelines, and customer ops.",
  },
  finance: {
    id: "finance",
    label: "Finance",
    description: "Banking, accounting, and spend tools.",
  },
  other: {
    id: "other",
    label: "Other",
    description: "Everything else memroos can talk to.",
  },
};

// ---------------------------------------------------------------------------
// Providers
// ---------------------------------------------------------------------------

const PROVIDERS: readonly Provider[] = [
  // ------------------------------ productivity ------------------------------
  {
    key: "slack",
    label: "Slack",
    icon: MessageCircle,
    description: "Read channels, send messages, and react on your behalf.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "slack",
    scopes: [
      "channels:read",
      "channels:history",
      "chat:write",
      "reactions:write",
      "users:read",
      "files:read",
    ],
  },
    {
      key: "circleback",
      label: "Circleback",
      icon: Video,
      description: "Search and reference meeting recordings, transcripts, and action items.",
      category: "productivity",
      authMode: "oauth",
      providerConfigKey: "circleback-mcp",
      scopes: ["meetings:read", "recordings:read", "transcripts:read"],
    },
    {
    key: "notion",
    label: "Notion",
    icon: FileText,
    description: "Search and edit pages, databases, and blocks.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "notion",
    scopes: [
      "read_content",
      "update_content",
      "insert_content",
      "read_user",
      "read_comments",
      "update_comments",
    ],
  },
  {
    key: "google-calendar",
    label: "Google Calendar",
    icon: Calendar,
    description: "List, create, and update events across your calendars.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "google-calendar",
    scopes: [
      "https://www.googleapis.com/auth/calendar.readonly",
      "https://www.googleapis.com/auth/calendar.events",
    ],
  },
  {
    key: "google-drive",
    label: "Google Drive",
    icon: Cloud,
    description: "Read and write files in your Drive.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "google-drive",
    scopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
    ],
  },

  // -------------------------------- developer -------------------------------
  {
    key: "github",
    label: "GitHub",
    icon: GitBranch,
    description: "Issues, PRs, and repo contents via the GitHub API.",
    category: "developer",
    authMode: "oauth",
    providerConfigKey: "github",
    scopes: ["repo", "read:user", "read:org", "workflow"],
  },
  {
    key: "linear",
    label: "Linear",
    icon: Code2,
    description: "Create and update issues, projects, and cycles.",
    category: "developer",
    authMode: "oauth",
    providerConfigKey: "linear",
    scopes: ["read", "write", "issues:create"],
  },
  {
    key: "supabase",
    label: "Supabase",
    icon: Database,
    description: "Query rows and manage tables in your Supabase project.",
    category: "developer",
    authMode: "api-key",
    apiKeyField: "Service role key (starts with eyJ...)",
    docsUrl: "https://supabase.com/dashboard/project/_/settings/api",
  },
  {
    key: "aws",
    label: "Amazon Web Services",
    icon: Cloud,
    description: "Read S3, SES, and select AWS services via IAM keys.",
    category: "developer",
    authMode: "api-key",
    apiKeyField: "Access key id (AKIA...) and secret access key",
    docsUrl: "https://console.aws.amazon.com/iam/home#/security_credentials",
  },

  // ------------------------------------ crm ---------------------------------
  {
    key: "hubspot",
    label: "HubSpot",
    icon: Users,
    description: "Contacts, companies, deals, and tickets.",
    category: "crm",
    authMode: "oauth",
    providerConfigKey: "hubspot",
    scopes: [
      "crm.objects.contacts.read",
      "crm.objects.contacts.write",
      "crm.objects.deals.read",
      "crm.objects.deals.write",
      "tickets",
    ],
  },
  {
    key: "salesforce",
    label: "Salesforce",
    icon: LayoutGrid,
    description: "Accounts, opportunities, and custom objects.",
    category: "crm",
    authMode: "oauth",
    providerConfigKey: "salesforce",
    scopes: ["api", "refresh_token", "offline_access"],
  },
  {
    key: "intercom",
    label: "Intercom",
    icon: MessageSquare,
    description: "Read and reply to conversations in your Intercom inbox.",
    category: "crm",
    authMode: "api-key",
    apiKeyField: "Access token (starts with dG9r...)",
    docsUrl: "https://app.intercom.com/a/apps/_/developer-hub",
  },

  // ---------------------------------- finance --------------------------------
  {
    key: "stripe",
    label: "Stripe",
    icon: Banknote,
    description: "Customers, charges, subscriptions, and payouts.",
    category: "finance",
    authMode: "api-key",
    apiKeyField: "Restricted secret key (rk_live_... or rk_test_...)",
    docsUrl: "https://dashboard.stripe.com/apikeys",
  },
  {
    key: "xero",
    label: "Xero",
    icon: Receipt,
    description: "Invoices, contacts, and reports from your Xero org.",
    category: "finance",
    authMode: "oauth",
    providerConfigKey: "xero",
    scopes: [
      "openid",
      "profile",
      "email",
      "accounting.transactions",
      "accounting.contacts",
      "accounting.reports.read",
    ],
  },
  {
    key: "plaid",
    label: "Plaid",
    icon: Layers,
    description: "Link bank accounts and pull balances and transactions.",
    category: "finance",
    authMode: "api-key",
    apiKeyField: "Client id and secret (from Plaid dashboard)",
    docsUrl: "https://dashboard.plaid.com/team/keys",
  },

  // ----------------------------------- other ---------------------------------
  {
    key: "generic-rest",
    label: "Generic REST API",
    icon: Box,
    description: "Hit any HTTPS endpoint with a bearer token.",
    category: "other",
    authMode: "api-key",
    apiKeyField: "Bearer token",
    docsUrl: "https://memroos.dev/docs/integrations/generic-rest",
  },
];

// ---------------------------------------------------------------------------
// Indexes & helpers
// ---------------------------------------------------------------------------

export const PROVIDERS_BY_KEY: Readonly<Record<string, Provider>> = Object.freeze(
  PROVIDERS.reduce<Record<string, Provider>>((acc, p) => {
    if (acc[p.key]) {
      throw new Error(`Duplicate provider key: ${p.key}`);
    }
    acc[p.key] = p;
    return acc;
  }, {}),
);

export const CATEGORIES: Readonly<Record<ProviderCategoryId, ProviderCategory>> =
  Object.freeze(CATEGORY_META);

/**
 * Returns the providers in `category`, in the declared priority order.
 */
export function getProvidersByCategory(
  category: ProviderCategoryId,
): Provider[] {
  return PROVIDERS.filter((p) => p.category === category);
}

/**
 * Returns every known category with its metadata, in directory order.
 */
export function getCategories(): ProviderCategory[] {
  return PROVIDER_CATEGORIES.map((id) => CATEGORY_META[id]);
}

/**
 * Returns every provider, grouped by category, in directory + priority order.
 * Useful for rendering the full directory in one pass.
 */
export function getGroupedProviders(): Array<{
  category: ProviderCategory;
  providers: Provider[];
}> {
  return getCategories().map((category) => ({
    category,
    providers: getProvidersByCategory(category.id),
  }));
}

/**
 * Look up a single provider by its key. Returns undefined if not found.
 */
export function getProvider(key: string): Provider | undefined {
  return PROVIDERS_BY_KEY[key];
}

/**
 * Convenience guards for narrowing union members.
 */
export function isOAuthProvider(p: Provider): p is OAuthProvider {
  return p.authMode === "oauth";
}

export function isApiKeyProvider(p: Provider): p is ApiKeyProvider {
  return p.authMode === "api-key";
}
