// AUTO-GENERATED by Phase 179 worker — see .beastmode/worker-runs/<ts>/prompt.md
import type { LucideIcon } from "lucide-react";
import {
  // Brand icons (Slack, Notion, Github) are not in lucide-react@1.7.0;
  // we use semantic equivalents until a brand-pack is added.
  MessageCircle, // Slack stand-in (chat)
  FileText, // Notion stand-in (docs)
  GitBranch, // GitHub stand-in (source control)
  Cloud,
  Calendar,
  Mail,
  Video,
  Code2,
} from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ProviderCategoryId =
  | "productivity"
  | "developer"
  | "crm"
  | "finance"
  | "other";

export type AuthMode = "oauth" | "api-key";

interface ProviderBase {
  /** Unique id; used as the Nango integration id. Lowercase, hyphen-safe. */
  key: string;
  /** Human-readable label shown in the connect CTA. */
  label: string;
  /** Lucide icon component. */
  icon: LucideIcon;
  /** Short one-line description for the directory card. */
  description: string;
  /** Category bucket. */
  category: ProviderCategoryId;
  /** Auth mode (this slice is single-mode only). */
  authMode: AuthMode;
}

export interface OAuthProvider extends ProviderBase {
  authMode: "oauth";
  /** Nango provider-config key (the slug registered in Nango). */
  providerConfigKey: string;
  /** OAuth scopes to request when initiating the connect flow. */
  scopes: string[];
  /**
   * Set when the Nango integration exists but cannot complete a connect yet —
   * e.g. a plain OAUTH2 provider whose client id/secret has not been filled in.
   * The card renders disabled with this reason instead of offering a Connect
   * button that fails with a raw Nango error.
   */
  unavailableReason?: string;
}

export interface ApiKeyProvider extends ProviderBase {
  authMode: "api-key";
  /** Label/placeholder for the API key input field. */
  apiKeyField: string;
  /** Link to the docs page where the user obtains the key. */
  docsUrl: string;
}

export type Provider = OAuthProvider | ApiKeyProvider;

export interface ProviderCategory {
  id: ProviderCategoryId;
  label: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Categories (ordered — the order here is the directory order)
// ---------------------------------------------------------------------------

export const PROVIDER_CATEGORIES: readonly ProviderCategoryId[] = [
  "productivity",
  "developer",
  "crm",
  "finance",
  "other",
] as const;

const CATEGORY_META: Record<ProviderCategoryId, ProviderCategory> = {
  productivity: {
    id: "productivity",
    label: "Productivity",
    description: "Docs, chat, calendars, and team workspaces.",
  },
  developer: {
    id: "developer",
    label: "Developer",
    description: "Source control, infra, and engineering tools.",
  },
  crm: {
    id: "crm",
    label: "CRM & Sales",
    description: "Contacts, pipelines, and customer ops.",
  },
  finance: {
    id: "finance",
    label: "Finance",
    description: "Banking, accounting, and spend tools.",
  },
  other: {
    id: "other",
    label: "Other",
    description: "Everything else memroos can talk to.",
  },
};

// ---------------------------------------------------------------------------
// Providers
// ---------------------------------------------------------------------------

const PROVIDERS: readonly Provider[] = [
  // ------------------------------ productivity ------------------------------
  {
    key: "slack",
    label: "Slack",
    icon: MessageCircle,
    description: "Read channels, send messages, and react on your behalf.",
    category: "productivity",
    authMode: "oauth",
    // Nango prod registers this as `slack-mcp`, not `slack` — see the
    // providerConfigKey/Nango parity test in __tests__/providers.test.ts.
    providerConfigKey: "slack-mcp",
    scopes: [
      "channels:read",
      "channels:history",
      "chat:write",
      "reactions:write",
      "users:read",
      "files:read",
    ],
  },
    {
      key: "circleback",
      label: "Circleback",
      icon: Video,
      description: "Search and reference meeting recordings, transcripts, and action items.",
      category: "productivity",
      authMode: "oauth",
      providerConfigKey: "circleback-mcp",
      scopes: ["meetings:read", "recordings:read", "transcripts:read"],
    },
    {
    key: "notion",
    label: "Notion",
    icon: FileText,
    description: "Search and edit pages, databases, and blocks.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "notion",
    scopes: [
      "read_content",
      "update_content",
      "insert_content",
      "read_user",
      "read_comments",
      "update_comments",
    ],
  },
  {
    key: "google-calendar",
    label: "Google Calendar",
    icon: Calendar,
    description: "List, create, and update events across your calendars.",
    category: "productivity",
    authMode: "oauth",
    // Nango prod registers this as `google-calendar-mcp`, not `google-calendar`.
    providerConfigKey: "google-calendar-mcp",
    // Needs a real Google Cloud OAuth app; unlike linear-mcp/circleback-mcp
    // (credentials: null = dynamic client registration, no app needed) there
    // is nothing Nango can register on our behalf.
    //
    // 2026-07-28: credentials WERE loaded into the Nango integration, and
    // POST /connect/sessions duly returned 201 — but that only proves Nango
    // accepted the shape. The actual consent screen then failed with
    // "Error 401: deleted_client — The OAuth client was deleted", because the
    // stored client no longer exists in Google Cloud. Both Google OAuth
    // clients on file are deleted, confirmed by probing
    // POST oauth2.googleapis.com/token (a live client answers invalid_grant;
    // a dead one answers deleted_client).
    //
    // So a 201 from connect/sessions is NOT sufficient evidence this works —
    // probe the client for liveness before clearing this field again.
    unavailableReason:
      "Needs a Google Cloud OAuth client that still exists — the configured client was deleted (Google error 401 deleted_client).",
    scopes: [
      "https://www.googleapis.com/auth/calendar.readonly",
      "https://www.googleapis.com/auth/calendar.events",
    ],
  },
  {
    key: "google-drive",
    label: "Google Drive",
    icon: Cloud,
    description: "Read and write files in your Drive.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "google-drive",
    scopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
    ],
  },
  {
    // Gmail has been configured in Nango as `google-mail` the whole time and
    // is already a first-class ContextSourceType, with the classification
    // cascade reading `gmail_labels` — but no card existed, so there was no
    // way to authorize it from the UI. Availability is resolved against the
    // live Nango integration list, so this card reflects reality rather than
    // a second hardcoded guess.
    key: "google-mail",
    label: "Gmail",
    icon: Mail,
    description: "Read mail and labels for memory and classification.",
    category: "productivity",
    authMode: "oauth",
    providerConfigKey: "google-mail",
    scopes: [
      "https://www.googleapis.com/auth/gmail.readonly",
      "https://www.googleapis.com/auth/gmail.metadata",
    ],
  },

  // -------------------------------- developer -------------------------------
  {
    key: "github",
    label: "GitHub",
    icon: GitBranch,
    description: "Issues, PRs, and repo contents via the GitHub API.",
    category: "developer",
    authMode: "oauth",
    providerConfigKey: "github",
    scopes: ["repo", "read:user", "read:org", "workflow"],
  },
  {
    key: "linear",
    label: "Linear",
    icon: Code2,
    description: "Create and update issues, projects, and cycles.",
    category: "developer",
    authMode: "oauth",
    // Nango prod registers both `linear` (plain OAuth, needs a Linear OAuth app
    // that requires workspace-admin rights) and `linear-mcp` (MCP-backed, no
    // admin app required). Pointing at `linear` sent Connect down the OAuth
    // branch and failed asking for a client ID/secret. Same shape as Circleback
    // above — see providerKeyFromConfigKey below for the card-matching this
    // key feeds. Verified against the live Nango prod integration list.
    providerConfigKey: "linear-mcp",
    scopes: ["read", "write", "issues:create"],
  },

  // ------------------------------- crm · finance · other -------------------
  // These categories are intentionally empty.
  //
  // They previously held supabase, aws, intercom, stripe, plaid and
  // generic-rest as `api-key` cards. Every one rendered a Connect button, and
  // none of them had a Nango integration behind it — Nango prod contains only
  // circleback-mcp, github, google, google-calendar-mcp, google-drive,
  // google-mail, linear-mcp, mcp-generic, notion and slack-mcp. The operator
  // never set any of the six up, so the cards were an aspirational list
  // presented as working functionality. Removed 2026-07-27.
  //
  // Re-add a provider here only alongside creating its Nango integration.

];

// ---------------------------------------------------------------------------
// Indexes & helpers
// ---------------------------------------------------------------------------

export const PROVIDERS_BY_KEY: Readonly<Record<string, Provider>> = Object.freeze(
  PROVIDERS.reduce<Record<string, Provider>>((acc, p) => {
    if (acc[p.key]) {
      throw new Error(`Duplicate provider key: ${p.key}`);
    }
    acc[p.key] = p;
    return acc;
  }, {}),
);

export const CATEGORIES: Readonly<Record<ProviderCategoryId, ProviderCategory>> =
  Object.freeze(CATEGORY_META);

/**
 * Returns the providers in `category`, in the declared priority order.
 */
export function getProvidersByCategory(
  category: ProviderCategoryId,
): Provider[] {
  return PROVIDERS.filter((p) => p.category === category);
}

/**
 * Returns every known category with its metadata, in directory order.
 */
export function getCategories(): ProviderCategory[] {
  return PROVIDER_CATEGORIES.map((id) => CATEGORY_META[id]);
}

/**
 * Returns every provider, grouped by category, in directory + priority order.
 * Useful for rendering the full directory in one pass.
 */
export function getGroupedProviders(): Array<{
  category: ProviderCategory;
  providers: Provider[];
}> {
  return getCategories().map((category) => ({
    category,
    providers: getProvidersByCategory(category.id),
  }));
}

/**
 * Look up a single provider by its key. Returns undefined if not found.
 */
export function getProvider(key: string): Provider | undefined {
  return PROVIDERS_BY_KEY[key];
}

/**
 * Convenience guards for narrowing union members.
 */
export function isOAuthProvider(p: Provider): p is OAuthProvider {
  return p.authMode === "oauth";
}

export function isApiKeyProvider(p: Provider): p is ApiKeyProvider {
  return p.authMode === "api-key";
}

/**
 * Map a Nango `provider_config_key` back to the memroos provider key.
 *
 * These are usually identical, but not always: Circleback is registered in
 * Nango as `circleback-mcp` while memroos knows it as `circleback`. Keying
 * connections by the raw Nango value meant a genuinely-connected Circleback
 * account never matched its card and the UI kept showing "Not connected"
 * (observed 2026-07-26 with two live connections present).
 *
 * Falls back to the input so an unrecognized integration still surfaces
 * rather than vanishing.
 */
export function providerKeyFromConfigKey(configKey: string): string {
  const match = PROVIDERS.find(
    (p) => isOAuthProvider(p) && p.providerConfigKey === configKey,
  );
  return match?.key ?? configKey;
}
