#!/usr/bin/env bash
# INSTALL-REPRO-05 regression: destructive-safe reinstall coverage.
#
# Two modes:
#   --fast     (default in CI)  structural checks only; finishes in seconds
#   --full     (manual / disposable-host)  actually runs a clean install +
#                                      reinstalls over it; takes minutes
#
# The fast mode is what CI runs on every PR. The full mode is what runs on a
# disposable host (CI on a job with `ephemeral: true` or a one-off VM) and
# captures the full /api/health evidence into a transcript directory passed
# via --transcript <dir>.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MODE="${1:-fast}"
TRANSCRIPT_DIR="${TRANSCRIPT_DIR:-/tmp/install-regression-transcript}"

# Resolve the CORE_SERVICES list dynamically so we never drift from compose.
CORE_SERVICES="$(grep -E '^[[:space:]]+memroos|^[[:space:]]+mem0|^[[:space:]]+orchestration|^[[:space:]]+neo4j|^[[:space:]]+ollama' \
  "$REPO_ROOT/docker-compose.local.yml" \
  | awk '{print $1}' | sort -u | grep -v '^services:' | grep -v '^$' | tr '\n' ',' | sed 's/,$//')"

pass() { printf '\033[32m✓\033[0m %s\n' "$1"; }
fail() { printf '\033[31m✗\033[0m %s\n' "$1"; exit 1; }
info() { printf '\033[34m•\033[0m %s\n' "$1"; }

structural_checks() {
  info "Run mode: fast (structural)"
  cd "$REPO_ROOT"

  # 1. install.sh accepts --local and defaults DOCKER_COMPOSE_FILE to docker-compose.local.yml.
  grep -q -- "--local" install.sh || fail "install.sh missing --local flag"
  grep -q "docker-compose.local.yml" install.sh || fail "install.sh default compose file not docker-compose.local.yml"
  pass "install.sh --local flag and docker-compose.local.yml default"

  # 2. docker-compose.local.yml exists in repo (was recovered from cordant-hermes-01).
  test -f docker-compose.local.yml || fail "docker-compose.local.yml missing"
  pass "docker-compose.local.yml present at repo root"

  # 3. README + docs/install-profiles.md reference the local stack.
  grep -q "docker-compose.local.yml" README.md || fail "README.md does not advertise docker-compose.local.yml"
  grep -q "docker-compose.local.yml" docs/install-profiles.md || fail "docs/install-profiles.md does not reference docker-compose.local.yml"
  pass "README + install-profiles.md advertise local stack"

  # 4. No sample macOS paths in runtime config.
  forbidden_paths_in_runtime() {
    grep -nE '^[[:space:]]*(KNOWLEDGE_BASE_PATH|AGENT_CONFIGS_PATH|APO_PROPOSALS_PATH|CLAUDE_MEMORY_PATH|GITNEXUS_REGISTRY|QWEN_MEMORY_PATH|HERMES_MEMORY_PATH|CODEX_MEMORY_PATH)=' .env.example \
      | grep -q '/Users/yourname\|/Users/USERNAME\|/home/yourname'
  }
  if forbidden_paths_in_runtime; then
    fail ".env.example still has literal /Users/yourname or /home/yourname runtime paths"
  fi
  pass ".env.example runtime paths use \${HOME} placeholders, not literal sample macOS paths"

  # 5. tsconfig.json narrow exclusion (only vitest configs).
  grep -qF '"**/vitest*.config.ts"' apps/memroos/tsconfig.json || fail "tsconfig.json missing narrow vitest exclusion"
  if grep -qF '"**/*.config.ts"' apps/memroos/tsconfig.json; then
    fail "tsconfig.json still excludes every *.config.ts (broad, masks next/playwright/postcss/eslint)"
  fi
  pass "tsconfig.json excludes only **/vitest*.config.ts (narrowest fix)"

  # 6. docker-compose.local.yml passes AGENT_CONFIGS_PATH + APO_PROPOSALS_PATH.
  grep -q "AGENT_CONFIGS_PATH:" docker-compose.local.yml || fail "compose missing AGENT_CONFIGS_PATH"
  grep -q "APO_PROPOSALS_PATH:" docker-compose.local.yml || fail "compose missing APO_PROPOSALS_PATH"
  pass "compose passes AGENT_CONFIGS_PATH + APO_PROPOSALS_PATH to the app container"

  # 7. install.sh .env expansion: must call envsubst OR have the fallback loop.
  if ! grep -q "envsubst" install.sh && ! grep -q "expanded=" install.sh; then
    fail "install.sh does not expand \${HOME} when generating .env (no envsubst and no fallback loop)"
  fi
  pass "install.sh expands \${HOME} when generating .env"

  # 8. .env generated by install.sh is mode 600.
  grep -q "chmod 600 .env" install.sh || fail "install.sh does not chmod 600 the generated .env"
  pass "install.sh sets .env to mode 600"

  # 9. Core services covered (memroos, mem0, orchestration, neo4j, ollama).
  for svc in memroos mem0 orchestration neo4j ollama; do
    grep -qE "^[[:space:]]+${svc}:" docker-compose.local.yml || fail "core service ${svc} missing from compose"
  done
  pass "all five core services present in compose"

  info "OK: all structural checks passed."
}

full_run() {
  info "Run mode: full (disposable-host)"
  mkdir -p "$TRANSCRIPT_DIR"
  cd "$TRANSCRIPT_DIR"

  if [[ -f .env ]]; then
    cp .env .env.prereinstall
    info "Backed up .env to .env.prereinstall"
  fi

  info "Step 1: docker compose down (without -v) to preserve named volumes"
  docker compose -f "$REPO_ROOT/docker-compose.local.yml" down 2>&1 | tee "$TRANSCRIPT_DIR/compose-down.log"

  info "Step 2: capture named volume inventory BEFORE reinstall"
  docker volume ls --format '{{.Name}}' | grep '^memroos-local_' > "$TRANSCRIPT_DIR/volumes-before.txt"
  cat "$TRANSCRIPT_DIR/volumes-before.txt"

  info "Step 3: install.sh --local (clean install)"
  bash "$REPO_ROOT/install.sh" --local 2>&1 | tee "$TRANSCRIPT_DIR/install.log" </dev/null

  info "Step 4: capture named volume inventory AFTER reinstall"
  docker volume ls --format '{{.Name}}' | grep '^memroos-local_' > "$TRANSCRIPT_DIR/volumes-after.txt"
  diff "$TRANSCRIPT_DIR/volumes-before.txt" "$TRANSCRIPT_DIR/volumes-after.txt" > "$TRANSCRIPT_DIR/volumes-diff.txt" || fail "named volumes changed across reinstall (regression)"

  info "Step 5: wait for memroos service healthy"
  for i in {1..60}; do
    if docker inspect "$(docker compose -f "$REPO_ROOT/docker-compose.local.yml" ps -q memroos)" \
       --format '{{.State.Health.Status}}' 2>/dev/null | grep -q healthy; then
      break
    fi
    sleep 5
  done

  info "Step 6: HTTP smoke checks on all five core services"
  declare -A PORTS=( [memroos]=3000 [mem0]=3201 [orchestration]=3210 [neo4j]=7474 [ollama]=11434 )
  for svc in memroos mem0 orchestration neo4j ollama; do
    port="${PORTS[$svc]}"
    code=$(curl -s -o "$TRANSCRIPT_DIR/${svc}.http" -w "%{http_code}" "http://127.0.0.1:${port}/" || echo "000")
    echo "$code" > "$TRANSCRIPT_DIR/${svc}.code"
    [[ "$code" == "200" || "$code" == "401" ]] || fail "${svc} returned ${code}, expected 200/401"
  done
  pass "core service HTTP smoke checks"

  info "Step 7: /api/health truthful for Agents and APO"
  curl -s http://127.0.0.1:3000/api/health | tee "$TRANSCRIPT_DIR/api-health.json"
  python3 - "$TRANSCRIPT_DIR/api-health.json" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
services = {s["name"]: s.get("status", "unknown") for s in d.get("services", [])}
for required in ("mem0", "Knowledge Index", "Graph Memory", "Agents", "APO"):
    status = services.get(required)
    if status not in ("up", "healthy", "ok"):
        sys.stderr.write(f"FAIL: {required} is {status!r}, expected up\n")
        sys.exit(1)
sys.stdout.write("PASS: /api/health truthful for all core subsystems incl. Agents and APO\n")
PY

  info "Step 8: secret/.env mode 600"
  mode=$(stat -c '%a' .env 2>/dev/null || stat -f '%p' .env | tail -c 4)
  [[ "$mode" == "600" ]] || fail ".env mode is ${mode}, expected 600"
  pass ".env is mode 600"

  info "Step 9: idempotent second install.sh run"
  bash "$REPO_ROOT/install.sh" --local 2>&1 | tee "$TRANSCRIPT_DIR/install-2.log" </dev/null
  last_exit="${PIPESTATUS[0]}"
  [[ "$last_exit" == "0" ]] || fail "second install.sh --local exited ${last_exit}"
  pass "second install.sh --local exited 0 (idempotent)"

  info "Step 10: repo-wide grep for /Users/yourname across deployed tree"
  if grep -rn '/Users/yourname' "$REPO_ROOT" --include='*.yml' --include='*.yaml' --include='*.sh' --include='*.example' --include='*.ts' --include='*.tsx' --include='*.js' --include='.env*' 2>/dev/null | grep -v '.planning/\|.git/\|.beastmode/\|.next/' > "$TRANSCRIPT_DIR/forbidden-paths.txt"; then
    info "WARNING: runtime config still has /Users/yourname hits — see $TRANSCRIPT_DIR/forbidden-paths.txt"
  else
    pass "no /Users/yourname in runtime config"
  fi

  info "OK: full disposable-host regression passed. Transcript at $TRANSCRIPT_DIR"
}

case "$MODE" in
  --fast|fast) structural_checks ;;
  --full|full) full_run ;;
  *) echo "usage: $0 [--fast|--full]  (or set TRANSCRIPT_DIR for --full)" >&2; exit 2 ;;
esac
