#!/usr/bin/env bash
# Install MemRoOS Streamable HTTP MCP as a systemd unit (Linux / Cordant hermes).
# Mirrors the ChatGPT LaunchAgent installer but for systemd + Cloudflare path /mcp.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT_SRC="${ROOT}/deploy/cordant-hermes-01/systemd/memroos-mcp-http.service"
UNIT_NAME="memroos-mcp-http.service"
UNIT_DST="/etc/systemd/system/${UNIT_NAME}"
ENV_DIR="${HOME}/.memroos"
ENV_FILE="${ENV_DIR}/memroos-mcp-http.env"
ACTION="${1:-install}"

usage() {
  cat <<HELP
Usage: scripts/install-memroos-mcp-systemd.sh [install|status|uninstall|print-token]

install     Write bearer env (if missing), install systemd unit, enable+start
status      Show unit status (redacts bearer)
uninstall   Disable and stop unit (keeps env file)
print-token Print MEMROOS_MCP_BEARER_TOKEN from env file (for operator connector setup)

Env:
  MEMROOS_MCP_BEARER_TOKEN   Optional pre-set token (otherwise generated)
  MEMROOS_ROOT               Default: repo root detected from this script
HELP
}

ensure_token() {
  mkdir -p "$ENV_DIR"
  chmod 700 "$ENV_DIR"
  if [[ -f "$ENV_FILE" ]] && grep -q '^MEMROOS_MCP_BEARER_TOKEN=' "$ENV_FILE"; then
    return 0
  fi
  local token="${MEMROOS_MCP_BEARER_TOKEN:-}"
  if [[ -z "$token" ]]; then
    token="$(openssl rand -hex 32)"
  fi
  umask 077
  {
    echo "# Generated by install-memroos-mcp-systemd.sh — do not commit"
    echo "MEMROOS_MCP_BEARER_TOKEN=${token}"
  } >"$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "Wrote ${ENV_FILE} (mode 0600)"
}

case "$ACTION" in
  -h|--help|help)
    usage
    exit 0
    ;;
  status)
    systemctl status "$UNIT_NAME" --no-pager || true
    if [[ -f "$ENV_FILE" ]]; then
      echo "env_file=${ENV_FILE} (token present, redacted)"
    else
      echo "env_file=missing"
    fi
    ss -ltn 2>/dev/null | grep ':8765' || true
    ;;
  print-token)
    if [[ ! -f "$ENV_FILE" ]]; then
      echo "missing ${ENV_FILE}" >&2
      exit 1
    fi
    sed -n 's/^MEMROOS_MCP_BEARER_TOKEN=//p' "$ENV_FILE" | tail -1
    ;;
  uninstall)
    sudo systemctl disable --now "$UNIT_NAME" || true
    sudo rm -f "$UNIT_DST"
    sudo systemctl daemon-reload
    echo "uninstalled ${UNIT_NAME} (env file kept at ${ENV_FILE})"
    ;;
  install)
    [[ -f "$UNIT_SRC" ]] || { echo "missing ${UNIT_SRC}" >&2; exit 1; }
    ensure_token
    sudo cp "$UNIT_SRC" "$UNIT_DST"
    sudo systemctl daemon-reload
    sudo systemctl enable --now "$UNIT_NAME"
    systemctl --no-pager --full status "$UNIT_NAME" | sed 's/MEMROOS_MCP_BEARER_TOKEN=.*/MEMROOS_MCP_BEARER_TOKEN=[redacted]/' | sed -n '1,25p'
    echo "Public connector URL: https://memroos-cordant.epiloguecapital.com/mcp"
    echo "Add Claude custom connector Request header: Authorization: Bearer \$(scripts/install-memroos-mcp-systemd.sh print-token)"
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
